params: !!python/object:argparse.Namespace
  batch_size: 12
  data_dir: ./data
  infer_path: ./data/test/val.png
  log_every_step: 50
  lr: 0.0001
  max_epoch: 100
  model_path: ./plt/ResNet.plt
  model_type: resnet18
  nums_gpu: 1
  optimizer: Adam
  test: false
  train: true
  val: false
  val_every_step: 1
